{
 "cells": [
  {
   "cell_type": "code",
   "id": "initial_id",
   "metadata": {
    "collapsed": true,
    "ExecuteTime": {
     "end_time": "2025-07-22T22:41:14.122001Z",
     "start_time": "2025-07-22T22:41:13.770606Z"
    }
   },
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.metrics import accuracy_score, classification_report, confusion_matrix\n",
    "\n",
    "import joblib"
   ],
   "outputs": [],
   "execution_count": 1
  },
  {
   "metadata": {
    "ExecuteTime": {
     "end_time": "2025-07-22T22:41:35.971738Z",
     "start_time": "2025-07-22T22:41:35.943914Z"
    }
   },
   "cell_type": "code",
   "source": [
    "df = pd.read_csv(\"glass.csv\")\n",
    "df.head()"
   ],
   "id": "f12d60a5b43a2e17",
   "outputs": [
    {
     "data": {
      "text/plain": [
       "        RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type\n",
       "0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1\n",
       "1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1\n",
       "2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1\n",
       "3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1\n",
       "4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1"
      ],
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>RI</th>\n",
       "      <th>Na</th>\n",
       "      <th>Mg</th>\n",
       "      <th>Al</th>\n",
       "      <th>Si</th>\n",
       "      <th>K</th>\n",
       "      <th>Ca</th>\n",
       "      <th>Ba</th>\n",
       "      <th>Fe</th>\n",
       "      <th>Type</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1.52101</td>\n",
       "      <td>13.64</td>\n",
       "      <td>4.49</td>\n",
       "      <td>1.10</td>\n",
       "      <td>71.78</td>\n",
       "      <td>0.06</td>\n",
       "      <td>8.75</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1.51761</td>\n",
       "      <td>13.89</td>\n",
       "      <td>3.60</td>\n",
       "      <td>1.36</td>\n",
       "      <td>72.73</td>\n",
       "      <td>0.48</td>\n",
       "      <td>7.83</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>1.51618</td>\n",
       "      <td>13.53</td>\n",
       "      <td>3.55</td>\n",
       "      <td>1.54</td>\n",
       "      <td>72.99</td>\n",
       "      <td>0.39</td>\n",
       "      <td>7.78</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>1.51766</td>\n",
       "      <td>13.21</td>\n",
       "      <td>3.69</td>\n",
       "      <td>1.29</td>\n",
       "      <td>72.61</td>\n",
       "      <td>0.57</td>\n",
       "      <td>8.22</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>1.51742</td>\n",
       "      <td>13.27</td>\n",
       "      <td>3.62</td>\n",
       "      <td>1.24</td>\n",
       "      <td>73.08</td>\n",
       "      <td>0.55</td>\n",
       "      <td>8.07</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "execution_count": 2
  },
  {
   "metadata": {
    "ExecuteTime": {
     "end_time": "2025-07-22T22:41:46.244925Z",
     "start_time": "2025-07-22T22:41:46.220835Z"
    }
   },
   "cell_type": "code",
   "source": [
    "df.info()\n",
    "df['Type'].value_counts()"
   ],
   "id": "6e03478ff66a02c0",
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "RangeIndex: 214 entries, 0 to 213\n",
      "Data columns (total 10 columns):\n",
      " #   Column  Non-Null Count  Dtype  \n",
      "---  ------  --------------  -----  \n",
      " 0   RI      214 non-null    float64\n",
      " 1   Na      214 non-null    float64\n",
      " 2   Mg      214 non-null    float64\n",
      " 3   Al      214 non-null    float64\n",
      " 4   Si      214 non-null    float64\n",
      " 5   K       214 non-null    float64\n",
      " 6   Ca      214 non-null    float64\n",
      " 7   Ba      214 non-null    float64\n",
      " 8   Fe      214 non-null    float64\n",
      " 9   Type    214 non-null    int64  \n",
      "dtypes: float64(9), int64(1)\n",
      "memory usage: 16.8 KB\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "Type\n",
       "2    76\n",
       "1    70\n",
       "7    29\n",
       "3    17\n",
       "5    13\n",
       "6     9\n",
       "Name: count, dtype: int64"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "execution_count": 3
  },
  {
   "metadata": {
    "ExecuteTime": {
     "end_time": "2025-07-22T22:41:53.501459Z",
     "start_time": "2025-07-22T22:41:53.496653Z"
    }
   },
   "cell_type": "code",
   "source": [
    "X = df.drop('Type', axis=1)\n",
    "y = df['Type']"
   ],
   "id": "4f65a0d8d92d15ce",
   "outputs": [],
   "execution_count": 4
  },
  {
   "metadata": {
    "ExecuteTime": {
     "end_time": "2025-07-22T22:41:59.710422Z",
     "start_time": "2025-07-22T22:41:59.696720Z"
    }
   },
   "cell_type": "code",
   "source": [
    "X_train, X_test, y_train, y_test = train_test_split(\n",
    "    X, y, test_size=0.2, random_state=42, stratify=y\n",
    ")"
   ],
   "id": "24cf0eec42b35977",
   "outputs": [],
   "execution_count": 5
  },
  {
   "metadata": {
    "ExecuteTime": {
     "end_time": "2025-07-22T22:42:06.387477Z",
     "start_time": "2025-07-22T22:42:06.381113Z"
    }
   },
   "cell_type": "code",
   "source": [
    "scaler = StandardScaler()\n",
    "X_train = scaler.fit_transform(X_train)\n",
    "X_test = scaler.transform(X_test)"
   ],
   "id": "5c7edf09f1bc23c4",
   "outputs": [],
   "execution_count": 6
  },
  {
   "metadata": {
    "ExecuteTime": {
     "end_time": "2025-07-22T22:42:12.763902Z",
     "start_time": "2025-07-22T22:42:12.685271Z"
    }
   },
   "cell_type": "code",
   "source": [
    "model = RandomForestClassifier(random_state=42)\n",
    "model.fit(X_train, y_train)"
   ],
   "id": "adea47315d1cdb38",
   "outputs": [
    {
     "data": {
      "text/plain": [
       "RandomForestClassifier(random_state=42)"
      ],
      "text/html": [
       "<style>#sk-container-id-1 {\n",
       "  /* Definition of color scheme common for light and dark mode */\n",
       "  --sklearn-color-text: #000;\n",
       "  --sklearn-color-text-muted: #666;\n",
       "  --sklearn-color-line: gray;\n",
       "  /* Definition of color scheme for unfitted estimators */\n",
       "  --sklearn-color-unfitted-level-0: #fff5e6;\n",
       "  --sklearn-color-unfitted-level-1: #f6e4d2;\n",
       "  --sklearn-color-unfitted-level-2: #ffe0b3;\n",
       "  --sklearn-color-unfitted-level-3: chocolate;\n",
       "  /* Definition of color scheme for fitted estimators */\n",
       "  --sklearn-color-fitted-level-0: #f0f8ff;\n",
       "  --sklearn-color-fitted-level-1: #d4ebff;\n",
       "  --sklearn-color-fitted-level-2: #b3dbfd;\n",
       "  --sklearn-color-fitted-level-3: cornflowerblue;\n",
       "\n",
       "  /* Specific color for light theme */\n",
       "  --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));\n",
       "  --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, white)));\n",
       "  --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));\n",
       "  --sklearn-color-icon: #696969;\n",
       "\n",
       "  @media (prefers-color-scheme: dark) {\n",
       "    /* Redefinition of color scheme for dark theme */\n",
       "    --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));\n",
       "    --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, #111)));\n",
       "    --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));\n",
       "    --sklearn-color-icon: #878787;\n",
       "  }\n",
       "}\n",
       "\n",
       "#sk-container-id-1 {\n",
       "  color: var(--sklearn-color-text);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 pre {\n",
       "  padding: 0;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 input.sk-hidden--visually {\n",
       "  border: 0;\n",
       "  clip: rect(1px 1px 1px 1px);\n",
       "  clip: rect(1px, 1px, 1px, 1px);\n",
       "  height: 1px;\n",
       "  margin: -1px;\n",
       "  overflow: hidden;\n",
       "  padding: 0;\n",
       "  position: absolute;\n",
       "  width: 1px;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-dashed-wrapped {\n",
       "  border: 1px dashed var(--sklearn-color-line);\n",
       "  margin: 0 0.4em 0.5em 0.4em;\n",
       "  box-sizing: border-box;\n",
       "  padding-bottom: 0.4em;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-container {\n",
       "  /* jupyter's `normalize.less` sets `[hidden] { display: none; }`\n",
       "     but bootstrap.min.css set `[hidden] { display: none !important; }`\n",
       "     so we also need the `!important` here to be able to override the\n",
       "     default hidden behavior on the sphinx rendered scikit-learn.org.\n",
       "     See: https://github.com/scikit-learn/scikit-learn/issues/21755 */\n",
       "  display: inline-block !important;\n",
       "  position: relative;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-text-repr-fallback {\n",
       "  display: none;\n",
       "}\n",
       "\n",
       "div.sk-parallel-item,\n",
       "div.sk-serial,\n",
       "div.sk-item {\n",
       "  /* draw centered vertical line to link estimators */\n",
       "  background-image: linear-gradient(var(--sklearn-color-text-on-default-background), var(--sklearn-color-text-on-default-background));\n",
       "  background-size: 2px 100%;\n",
       "  background-repeat: no-repeat;\n",
       "  background-position: center center;\n",
       "}\n",
       "\n",
       "/* Parallel-specific style estimator block */\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item::after {\n",
       "  content: \"\";\n",
       "  width: 100%;\n",
       "  border-bottom: 2px solid var(--sklearn-color-text-on-default-background);\n",
       "  flex-grow: 1;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel {\n",
       "  display: flex;\n",
       "  align-items: stretch;\n",
       "  justify-content: center;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  position: relative;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item:first-child::after {\n",
       "  align-self: flex-end;\n",
       "  width: 50%;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item:last-child::after {\n",
       "  align-self: flex-start;\n",
       "  width: 50%;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item:only-child::after {\n",
       "  width: 0;\n",
       "}\n",
       "\n",
       "/* Serial-specific style estimator block */\n",
       "\n",
       "#sk-container-id-1 div.sk-serial {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "  align-items: center;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  padding-right: 1em;\n",
       "  padding-left: 1em;\n",
       "}\n",
       "\n",
       "\n",
       "/* Toggleable style: style used for estimator/Pipeline/ColumnTransformer box that is\n",
       "clickable and can be expanded/collapsed.\n",
       "- Pipeline and ColumnTransformer use this feature and define the default style\n",
       "- Estimators will overwrite some part of the style using the `sk-estimator` class\n",
       "*/\n",
       "\n",
       "/* Pipeline and ColumnTransformer style (default) */\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable {\n",
       "  /* Default theme specific background. It is overwritten whether we have a\n",
       "  specific estimator or a Pipeline/ColumnTransformer */\n",
       "  background-color: var(--sklearn-color-background);\n",
       "}\n",
       "\n",
       "/* Toggleable label */\n",
       "#sk-container-id-1 label.sk-toggleable__label {\n",
       "  cursor: pointer;\n",
       "  display: flex;\n",
       "  width: 100%;\n",
       "  margin-bottom: 0;\n",
       "  padding: 0.5em;\n",
       "  box-sizing: border-box;\n",
       "  text-align: center;\n",
       "  align-items: start;\n",
       "  justify-content: space-between;\n",
       "  gap: 0.5em;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 label.sk-toggleable__label .caption {\n",
       "  font-size: 0.6rem;\n",
       "  font-weight: lighter;\n",
       "  color: var(--sklearn-color-text-muted);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 label.sk-toggleable__label-arrow:before {\n",
       "  /* Arrow on the left of the label */\n",
       "  content: \"▸\";\n",
       "  float: left;\n",
       "  margin-right: 0.25em;\n",
       "  color: var(--sklearn-color-icon);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 label.sk-toggleable__label-arrow:hover:before {\n",
       "  color: var(--sklearn-color-text);\n",
       "}\n",
       "\n",
       "/* Toggleable content - dropdown */\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable__content {\n",
       "  display: none;\n",
       "  text-align: left;\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable__content.fitted {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable__content pre {\n",
       "  margin: 0.2em;\n",
       "  border-radius: 0.25em;\n",
       "  color: var(--sklearn-color-text);\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable__content.fitted pre {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 input.sk-toggleable__control:checked~div.sk-toggleable__content {\n",
       "  /* Expand drop-down */\n",
       "  display: block;\n",
       "  width: 100%;\n",
       "  overflow: visible;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {\n",
       "  content: \"▾\";\n",
       "}\n",
       "\n",
       "/* Pipeline/ColumnTransformer-specific style */\n",
       "\n",
       "#sk-container-id-1 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  color: var(--sklearn-color-text);\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-label.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "/* Estimator-specific style */\n",
       "\n",
       "/* Colorize estimator box */\n",
       "#sk-container-id-1 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-estimator.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-label label.sk-toggleable__label,\n",
       "#sk-container-id-1 div.sk-label label {\n",
       "  /* The background is the default theme color */\n",
       "  color: var(--sklearn-color-text-on-default-background);\n",
       "}\n",
       "\n",
       "/* On hover, darken the color of the background */\n",
       "#sk-container-id-1 div.sk-label:hover label.sk-toggleable__label {\n",
       "  color: var(--sklearn-color-text);\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "/* Label box, darken color on hover, fitted */\n",
       "#sk-container-id-1 div.sk-label.fitted:hover label.sk-toggleable__label.fitted {\n",
       "  color: var(--sklearn-color-text);\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "/* Estimator label */\n",
       "\n",
       "#sk-container-id-1 div.sk-label label {\n",
       "  font-family: monospace;\n",
       "  font-weight: bold;\n",
       "  display: inline-block;\n",
       "  line-height: 1.2em;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-label-container {\n",
       "  text-align: center;\n",
       "}\n",
       "\n",
       "/* Estimator-specific */\n",
       "#sk-container-id-1 div.sk-estimator {\n",
       "  font-family: monospace;\n",
       "  border: 1px dotted var(--sklearn-color-border-box);\n",
       "  border-radius: 0.25em;\n",
       "  box-sizing: border-box;\n",
       "  margin-bottom: 0.5em;\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-estimator.fitted {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-0);\n",
       "}\n",
       "\n",
       "/* on hover */\n",
       "#sk-container-id-1 div.sk-estimator:hover {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-estimator.fitted:hover {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "/* Specification for estimator info (e.g. \"i\" and \"?\") */\n",
       "\n",
       "/* Common style for \"i\" and \"?\" */\n",
       "\n",
       ".sk-estimator-doc-link,\n",
       "a:link.sk-estimator-doc-link,\n",
       "a:visited.sk-estimator-doc-link {\n",
       "  float: right;\n",
       "  font-size: smaller;\n",
       "  line-height: 1em;\n",
       "  font-family: monospace;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  border-radius: 1em;\n",
       "  height: 1em;\n",
       "  width: 1em;\n",
       "  text-decoration: none !important;\n",
       "  margin-left: 0.5em;\n",
       "  text-align: center;\n",
       "  /* unfitted */\n",
       "  border: var(--sklearn-color-unfitted-level-1) 1pt solid;\n",
       "  color: var(--sklearn-color-unfitted-level-1);\n",
       "}\n",
       "\n",
       ".sk-estimator-doc-link.fitted,\n",
       "a:link.sk-estimator-doc-link.fitted,\n",
       "a:visited.sk-estimator-doc-link.fitted {\n",
       "  /* fitted */\n",
       "  border: var(--sklearn-color-fitted-level-1) 1pt solid;\n",
       "  color: var(--sklearn-color-fitted-level-1);\n",
       "}\n",
       "\n",
       "/* On hover */\n",
       "div.sk-estimator:hover .sk-estimator-doc-link:hover,\n",
       ".sk-estimator-doc-link:hover,\n",
       "div.sk-label-container:hover .sk-estimator-doc-link:hover,\n",
       ".sk-estimator-doc-link:hover {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-3);\n",
       "  color: var(--sklearn-color-background);\n",
       "  text-decoration: none;\n",
       "}\n",
       "\n",
       "div.sk-estimator.fitted:hover .sk-estimator-doc-link.fitted:hover,\n",
       ".sk-estimator-doc-link.fitted:hover,\n",
       "div.sk-label-container:hover .sk-estimator-doc-link.fitted:hover,\n",
       ".sk-estimator-doc-link.fitted:hover {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-3);\n",
       "  color: var(--sklearn-color-background);\n",
       "  text-decoration: none;\n",
       "}\n",
       "\n",
       "/* Span, style for the box shown on hovering the info icon */\n",
       ".sk-estimator-doc-link span {\n",
       "  display: none;\n",
       "  z-index: 9999;\n",
       "  position: relative;\n",
       "  font-weight: normal;\n",
       "  right: .2ex;\n",
       "  padding: .5ex;\n",
       "  margin: .5ex;\n",
       "  width: min-content;\n",
       "  min-width: 20ex;\n",
       "  max-width: 50ex;\n",
       "  color: var(--sklearn-color-text);\n",
       "  box-shadow: 2pt 2pt 4pt #999;\n",
       "  /* unfitted */\n",
       "  background: var(--sklearn-color-unfitted-level-0);\n",
       "  border: .5pt solid var(--sklearn-color-unfitted-level-3);\n",
       "}\n",
       "\n",
       ".sk-estimator-doc-link.fitted span {\n",
       "  /* fitted */\n",
       "  background: var(--sklearn-color-fitted-level-0);\n",
       "  border: var(--sklearn-color-fitted-level-3);\n",
       "}\n",
       "\n",
       ".sk-estimator-doc-link:hover span {\n",
       "  display: block;\n",
       "}\n",
       "\n",
       "/* \"?\"-specific style due to the `<a>` HTML tag */\n",
       "\n",
       "#sk-container-id-1 a.estimator_doc_link {\n",
       "  float: right;\n",
       "  font-size: 1rem;\n",
       "  line-height: 1em;\n",
       "  font-family: monospace;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  border-radius: 1rem;\n",
       "  height: 1rem;\n",
       "  width: 1rem;\n",
       "  text-decoration: none;\n",
       "  /* unfitted */\n",
       "  color: var(--sklearn-color-unfitted-level-1);\n",
       "  border: var(--sklearn-color-unfitted-level-1) 1pt solid;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 a.estimator_doc_link.fitted {\n",
       "  /* fitted */\n",
       "  border: var(--sklearn-color-fitted-level-1) 1pt solid;\n",
       "  color: var(--sklearn-color-fitted-level-1);\n",
       "}\n",
       "\n",
       "/* On hover */\n",
       "#sk-container-id-1 a.estimator_doc_link:hover {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-3);\n",
       "  color: var(--sklearn-color-background);\n",
       "  text-decoration: none;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 a.estimator_doc_link.fitted:hover {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-3);\n",
       "}\n",
       "\n",
       ".estimator-table summary {\n",
       "    padding: .5rem;\n",
       "    font-family: monospace;\n",
       "    cursor: pointer;\n",
       "}\n",
       "\n",
       ".estimator-table details[open] {\n",
       "    padding-left: 0.1rem;\n",
       "    padding-right: 0.1rem;\n",
       "    padding-bottom: 0.3rem;\n",
       "}\n",
       "\n",
       ".estimator-table .parameters-table {\n",
       "    margin-left: auto !important;\n",
       "    margin-right: auto !important;\n",
       "}\n",
       "\n",
       ".estimator-table .parameters-table tr:nth-child(odd) {\n",
       "    background-color: #fff;\n",
       "}\n",
       "\n",
       ".estimator-table .parameters-table tr:nth-child(even) {\n",
       "    background-color: #f6f6f6;\n",
       "}\n",
       "\n",
       ".estimator-table .parameters-table tr:hover {\n",
       "    background-color: #e0e0e0;\n",
       "}\n",
       "\n",
       ".estimator-table table td {\n",
       "    border: 1px solid rgba(106, 105, 104, 0.232);\n",
       "}\n",
       "\n",
       ".user-set td {\n",
       "    color:rgb(255, 94, 0);\n",
       "    text-align: left;\n",
       "}\n",
       "\n",
       ".user-set td.value pre {\n",
       "    color:rgb(255, 94, 0) !important;\n",
       "    background-color: transparent !important;\n",
       "}\n",
       "\n",
       ".default td {\n",
       "    color: black;\n",
       "    text-align: left;\n",
       "}\n",
       "\n",
       ".user-set td i,\n",
       ".default td i {\n",
       "    color: black;\n",
       "}\n",
       "\n",
       ".copy-paste-icon {\n",
       "    background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48IS0tIUZvbnQgQXdlc29tZSBGcmVlIDYuNy4yIGJ5IEBmb250YXdlc29tZSAtIGh0dHBzOi8vZm9udGF3ZXNvbWUuY29tIExpY2Vuc2UgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbS9saWNlbnNlL2ZyZWUgQ29weXJpZ2h0IDIwMjUgRm9udGljb25zLCBJbmMuLS0+PHBhdGggZD0iTTIwOCAwTDMzMi4xIDBjMTIuNyAwIDI0LjkgNS4xIDMzLjkgMTQuMWw2Ny45IDY3LjljOSA5IDE0LjEgMjEuMiAxNC4xIDMzLjlMNDQ4IDMzNmMwIDI2LjUtMjEuNSA0OC00OCA0OGwtMTkyIDBjLTI2LjUgMC00OC0yMS41LTQ4LTQ4bDAtMjg4YzAtMjYuNSAyMS41LTQ4IDQ4LTQ4ek00OCAxMjhsODAgMCAwIDY0LTY0IDAgMCAyNTYgMTkyIDAgMC0zMiA2NCAwIDAgNDhjMCAyNi41LTIxLjUgNDgtNDggNDhMNDggNTEyYy0yNi41IDAtNDgtMjEuNS00OC00OEwwIDE3NmMwLTI2LjUgMjEuNS00OCA0OC00OHoiLz48L3N2Zz4=);\n",
       "    background-repeat: no-repeat;\n",
       "    background-size: 14px 14px;\n",
       "    background-position: 0;\n",
       "    display: inline-block;\n",
       "    width: 14px;\n",
       "    height: 14px;\n",
       "    cursor: pointer;\n",
       "}\n",
       "</style><body><div id=\"sk-container-id-1\" class=\"sk-top-container\"><div class=\"sk-text-repr-fallback\"><pre>RandomForestClassifier(random_state=42)</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br />On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class=\"sk-container\" hidden><div class=\"sk-item\"><div class=\"sk-estimator fitted sk-toggleable\"><input class=\"sk-toggleable__control sk-hidden--visually\" id=\"sk-estimator-id-1\" type=\"checkbox\" checked><label for=\"sk-estimator-id-1\" class=\"sk-toggleable__label fitted sk-toggleable__label-arrow\"><div><div>RandomForestClassifier</div></div><div><a class=\"sk-estimator-doc-link fitted\" rel=\"noreferrer\" target=\"_blank\" href=\"https://scikit-learn.org/1.7/modules/generated/sklearn.ensemble.RandomForestClassifier.html\">?<span>Documentation for RandomForestClassifier</span></a><span class=\"sk-estimator-doc-link fitted\">i<span>Fitted</span></span></div></label><div class=\"sk-toggleable__content fitted\" data-param-prefix=\"\">\n",
       "        <div class=\"estimator-table\">\n",
       "            <details>\n",
       "                <summary>Parameters</summary>\n",
       "                <table class=\"parameters-table\">\n",
       "                  <tbody>\n",
       "                    \n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('n_estimators',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">n_estimators&nbsp;</td>\n",
       "            <td class=\"value\">100</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('criterion',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">criterion&nbsp;</td>\n",
       "            <td class=\"value\">&#x27;gini&#x27;</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('max_depth',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">max_depth&nbsp;</td>\n",
       "            <td class=\"value\">None</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('min_samples_split',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">min_samples_split&nbsp;</td>\n",
       "            <td class=\"value\">2</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('min_samples_leaf',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">min_samples_leaf&nbsp;</td>\n",
       "            <td class=\"value\">1</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('min_weight_fraction_leaf',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">min_weight_fraction_leaf&nbsp;</td>\n",
       "            <td class=\"value\">0.0</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('max_features',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">max_features&nbsp;</td>\n",
       "            <td class=\"value\">&#x27;sqrt&#x27;</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('max_leaf_nodes',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">max_leaf_nodes&nbsp;</td>\n",
       "            <td class=\"value\">None</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('min_impurity_decrease',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">min_impurity_decrease&nbsp;</td>\n",
       "            <td class=\"value\">0.0</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('bootstrap',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">bootstrap&nbsp;</td>\n",
       "            <td class=\"value\">True</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('oob_score',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">oob_score&nbsp;</td>\n",
       "            <td class=\"value\">False</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('n_jobs',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">n_jobs&nbsp;</td>\n",
       "            <td class=\"value\">None</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"user-set\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('random_state',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">random_state&nbsp;</td>\n",
       "            <td class=\"value\">42</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('verbose',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">verbose&nbsp;</td>\n",
       "            <td class=\"value\">0</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('warm_start',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">warm_start&nbsp;</td>\n",
       "            <td class=\"value\">False</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('class_weight',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">class_weight&nbsp;</td>\n",
       "            <td class=\"value\">None</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('ccp_alpha',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">ccp_alpha&nbsp;</td>\n",
       "            <td class=\"value\">0.0</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('max_samples',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">max_samples&nbsp;</td>\n",
       "            <td class=\"value\">None</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('monotonic_cst',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">monotonic_cst&nbsp;</td>\n",
       "            <td class=\"value\">None</td>\n",
       "        </tr>\n",
       "    \n",
       "                  </tbody>\n",
       "                </table>\n",
       "            </details>\n",
       "        </div>\n",
       "    </div></div></div></div></div><script>function copyToClipboard(text, element) {\n",
       "    // Get the parameter prefix from the closest toggleable content\n",
       "    const toggleableContent = element.closest('.sk-toggleable__content');\n",
       "    const paramPrefix = toggleableContent ? toggleableContent.dataset.paramPrefix : '';\n",
       "    const fullParamName = paramPrefix ? `${paramPrefix}${text}` : text;\n",
       "\n",
       "    const originalStyle = element.style;\n",
       "    const computedStyle = window.getComputedStyle(element);\n",
       "    const originalWidth = computedStyle.width;\n",
       "    const originalHTML = element.innerHTML.replace('Copied!', '');\n",
       "\n",
       "    navigator.clipboard.writeText(fullParamName)\n",
       "        .then(() => {\n",
       "            element.style.width = originalWidth;\n",
       "            element.style.color = 'green';\n",
       "            element.innerHTML = \"Copied!\";\n",
       "\n",
       "            setTimeout(() => {\n",
       "                element.innerHTML = originalHTML;\n",
       "                element.style = originalStyle;\n",
       "            }, 2000);\n",
       "        })\n",
       "        .catch(err => {\n",
       "            console.error('Failed to copy:', err);\n",
       "            element.style.color = 'red';\n",
       "            element.innerHTML = \"Failed!\";\n",
       "            setTimeout(() => {\n",
       "                element.innerHTML = originalHTML;\n",
       "                element.style = originalStyle;\n",
       "            }, 2000);\n",
       "        });\n",
       "    return false;\n",
       "}\n",
       "\n",
       "document.querySelectorAll('.fa-regular.fa-copy').forEach(function(element) {\n",
       "    const toggleableContent = element.closest('.sk-toggleable__content');\n",
       "    const paramPrefix = toggleableContent ? toggleableContent.dataset.paramPrefix : '';\n",
       "    const paramName = element.parentElement.nextElementSibling.textContent.trim();\n",
       "    const fullParamName = paramPrefix ? `${paramPrefix}${paramName}` : paramName;\n",
       "\n",
       "    element.setAttribute('title', fullParamName);\n",
       "});\n",
       "</script></body>"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "execution_count": 7
  },
  {
   "metadata": {
    "ExecuteTime": {
     "end_time": "2025-07-22T22:42:20.557945Z",
     "start_time": "2025-07-22T22:42:20.538698Z"
    }
   },
   "cell_type": "code",
   "source": [
    "y_pred = model.predict(X_test)\n",
    "print(\"✅ Accuracy Score:\", accuracy_score(y_test, y_pred))\n",
    "print(\"\\n📋 Classification Report:\\n\", classification_report(y_test, y_pred))"
   ],
   "id": "4ad231d56e2dc45d",
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "✅ Accuracy Score: 0.8372093023255814\n",
      "\n",
      "📋 Classification Report:\n",
      "               precision    recall  f1-score   support\n",
      "\n",
      "           1       0.76      0.93      0.84        14\n",
      "           2       0.85      0.73      0.79        15\n",
      "           3       1.00      0.67      0.80         3\n",
      "           5       1.00      0.67      0.80         3\n",
      "           6       0.67      1.00      0.80         2\n",
      "           7       1.00      1.00      1.00         6\n",
      "\n",
      "    accuracy                           0.84        43\n",
      "   macro avg       0.88      0.83      0.84        43\n",
      "weighted avg       0.85      0.84      0.84        43\n",
      "\n"
     ]
    }
   ],
   "execution_count": 8
  },
  {
   "metadata": {
    "ExecuteTime": {
     "end_time": "2025-07-22T22:42:29.295513Z",
     "start_time": "2025-07-22T22:42:29.099333Z"
    }
   },
   "cell_type": "code",
   "source": [
    "cm = confusion_matrix(y_test, y_pred)\n",
    "plt.figure(figsize=(8, 6))\n",
    "sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')\n",
    "plt.title(\"Confusion Matrix\")\n",
    "plt.xlabel(\"Predicted\")\n",
    "plt.ylabel(\"Actual\")\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ],
   "id": "9a75705997b55803",
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<Figure size 800x600 with 2 Axes>"
      ],
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAtsAAAJOCAYAAABm28tYAAAAOnRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjEwLjMsIGh0dHBzOi8vbWF0cGxvdGxpYi5vcmcvZiW1igAAAAlwSFlzAAAPYQAAD2EBqD+naQAARzFJREFUeJzt3QmcTfX/x/HPGWPMWMY2FCpKka2MsRYpKSpF2y/KGtGCUiGyZc2SUmMLEyKEVNJiK7/qJ7KTJQbRTzQjo5gxY5n/4/v9P+78ZixluOd879zv69njPMw9M+793vvtjM9938/5Hic9PT1dAAAAAPhdiP/vEgAAAIBCsQ0AAAC4hGIbAAAAcAnFNgAAAOASim0AAADAJRTbAAAAgEsotgEAAACXUGwDAAAALqHYBgDLcW0zAHAPxTYAz2zevFm6d+8ut99+u9x0003SsGFD6du3r+zfv9+1x5w6darceuut+vHGjRvnl/tctWqVlC9fXv/pNt9jqe27774778/Ex8dn/Myvv/560fedlpYmQ4cOlYULF/7jz6r7fuedd7I1dgAAxTYAj8ycOVOaN28uhw8flpdeekkmTZokHTt2lNWrV8sjjzwi27dv9/tjHjt2TIYPH64L7SlTpsiDDz7ol/utVKmSzJkzR//plZCQEPnyyy/P+73PP//8ku7z999/l2nTpsmpU6f+8WfV83300Ucv6XEAwGYU2wBct3btWhkyZIg8/vjjEhcXJ/fff7/UqlVL/vWvf8msWbMkT5480rt3b78/7tGjR+XMmTM6Qa9Ro4aUKFHCL/ebP39+qVq1qv7TK9WqVZMlS5actzBWxXaFChVcfXz1fK+88kpXHwMAghHFNgDXqVS5QIEC8uKLL57zvSJFisgrr7wid955pyQnJ+t9p0+f1km4KspVKq3aTkaNGiWpqakZf0/9nbZt28r8+fOlUaNGUrlyZWnatKn8+9//1t//6KOPpEGDBvprVcirNghF7VN/NzP1s5lbME6cOCEDBgyQ2267Td9v48aN9XP4uzYS1SLTvn17/SZCFcZPP/207Ny585y/s3LlSnnyySfl5ptv1u0tI0eO1M/3n9x7772SlJQkP/zwQ5b96hOBvXv3yj333HPO31m6dKl+gxMdHZ3xPNTrqqjnql5zpVevXhmvlXpt2rRpI/3799fPQz2uGl/mNpLOnTtLlSpVZPfu3RmPpb6nCn71SQUA4H8otgG4fvKd6jWuU6eOREREnPdnVEH33HPPSd68efXtfv36ybBhw3QiPX78eHniiSdkxowZ8uyzz2Y5mW/Lli26CO7atauMHTtWcuXKJV26dNGJtirQY2Nj9c8988wzug3iYqk+ZlW09+zZU9+/KkpHjBihC/vzUQVwixYtMv7u4MGD5bffftNtM6qfOrOXX35ZYmJiZMKECdKkSROZPHmyzJ079x/HdP3118sNN9xwTivJokWLpGbNmlKsWLEs+7/55hv9mqpWF9Wrrorhq6++WgYOHCgbN26U4sWLZ3l9fF8ra9as0eNXr6lq+VGva2bqjYiaK1WQ++ZBPR/1JkKNBQDwP6GZvgYAvzty5IhOpK+66qqL+vldu3bJvHnzdJGneroVlQCr4rBHjx66CK5fv77e/9dff+lU+pprrtG3VQHYsmVLXfyqtNvXWqG+r9ogLpZKZ9Vj3nffffq2SqvVfRctWvS8P//GG29I6dKl5d13380oTOvWrSt33XWXvP322zJmzJiMn1V9z6oIVtQbEJU+q8JYFeb/RKXX06dP18VuaGhoRguJStHP9zqqHvVXX301Y59KuNVzUSm7StYzvz4VK1bM+DnVqqKK8gu1jURFRelCu1u3bvqNgur7LleunDz//PP/+BwAwDYk2wBc5Ss+L6ZVQvG1IfgKXR91W91X5tYN1YLiK7QVX3GYkpJyWWNWBemHH34oTz31lE7U1WopqkBWafnZVOuLaiFRhXDmBDgyMlLuuOOOc9oqVMGbmRqzr30mu60kKqE+dOiQ3H333ef8bIcOHeT111+X48eP6+RZFeUTJ07MWIXk7xQqVOgf+7PVWNQbGvUphHp9VJtPWFjYRT0PALAJxTYAVxUsWFDy5csnBw4cuODPqGJTtX4ovj/PbotQSW7hwoV1mu1zdluK4zj6T3VS5OVQafALL7yg+5oHDRqk21lU8ny+FVPUeFRri0p7z6b2ZR6vEh4efs4qIxe7zvW1116r02hfK4kqoFWCrl7js/3xxx+6paZ69er6RFTVRqJWZ1H+6fHUfF0MlZyr17pMmTJ6bACAc1FsA3CdKghVIp35BMfMVIpcu3Zt+emnnzIKx4SEhCw/c/LkSd2Sogruy3V2yn52sqwSWtXH/MUXX8jXX3+dkd6q1pazqRM/VZGfmJh4zvfUc1ApsT+pRFmtSqJeD1V0n/0JQObecJW4q3XGN2zYoJ+LP1d8UZ8eqL561T7y888/61VmAADnotgG4Dp14pxqf3jrrbfOW5CqQk2dAKhO5vOdYKdO/MtM3VZFsjq58HKo5foOHjx4ztKEPmolEtUe4SseS5YsqU/QVEXt+dJ51cutVvpQxWzmIl4l2qoX+3LHezbVrqJeS3VCovoUwLeiyNnUc1LtJaolxtfe4VupxZf8n33iY3aoPnX1OqrEXPXJq970s08GBQBwgiQAD6iTE9XJc6rYVgVZs2bNdEKtlsZTq32oxNtXiKuiW7UnqOJNpadqfext27bp1TJU4VivXr3LGovqo1a9y2pTJwkuX748y3J6qs1DFf3q8XLnzq2XvNuzZ48sWLBAF+HnoxJvteyfOqFTLbWnUmd1sqTqjfadDOkvakURteyeGr86AdO3gsvZ1JKJ6sqQ6rmo/ut169bpMakU3tfTrlJ5RS1HWLZsWf16XAzVh6562dUJkqqFRLXcqLRdLRs4e/bsyyriASDYUGwD8IRqy1ArXqh1ntXyeCqVVReZUScdqtU0Ml9wRl0AR63uoZbaU1eaVCuRtG7dWi/9p3qcL0enTp10P7Mq8lVRrB5fPZ4an49aiUMV/yrdVsm7WoVEXeXyQqttqFVF3nvvPf0GQa0lrpJk1Sutrl6pluvzN9VKolpELtRCoqiTI1W/udoUVRS/9tpr8umnn+ql/Xwpf7t27fSyiCtWrJDvv//+Hx9btdyodblV+4h6g+Hr8VatNuo1VEsZqtcYAPD/nPSLPTMHAAAAQLbQsw0AAAC4hGIbAAAAcAnFNgAAAOASim0AAADAJRTbAAAAgEsotgEAAACXUGwDAAAALgnKi9pERHc2PQTr7V3xpukhWK9g3tymhwAACADhofbVaSnrYyVQkGwDAAAALgmw9zoAAAAIao5dWa9dzxYAAADwEMk2AAAAvOM4YhOSbQAAAMAlJNsAAADwjmNX1mvXswUAAAA8RLINAAAA7zj0bAMAAADwA5JtAAAAeMexK+u169kCAAAAHiLZBgAAgHccerYBAAAA+AHJNgAAALzj2JX12vVsAQAAAA+RbAMAAMA7Dj3bAAAAAPyAZBsAAADecezKeu16tgAAAICHSLYBAADgHYeebQAAAAB+QLINAAAA7zh2Zb12PVsAAADAQyTbAAAA8I5DzzYAAAAAPyDZBgAAgHccu7Jeu54tAAAA4CGSbQAAAHjHsSvrtevZAgAAAB4i2QYAAIB3QliNBAAAAIAfkGwDAADAO45dWa9dzxYAAADwEMU2AAAAvL2CpOPydonS0tKkSZMmsmrVqox9GzZskObNm0t0dLQ0atRI5s6dm637pNgGAACA9VJTU+XFF1+UnTt3ZuxLSEiQp556SmrWrCkLFiyQrl27yqBBg+Sbb7656Pul2A4QYblDZc3c3lIv5oaMfQ3rVJBVc16RP1aO1n/efWtFo2O0iXpn2+axZrJ+7WrTQ7Hyl13/vr2lbu3qcmf9ujJtapzpIVmHOTCPOTCPOXC5Z9txecumXbt2yb/+9S/Zt29flv1Lly6VqKgoXYSXKVNG7rvvPmnWrJksXLjwou+bEyQDQJ6wUJk2tK1Uur5kxr7rro6SOW88JQPGLpSF32ySB+64WT4c/ZTc1GyQ7PvtD6PjteEX7MA+PWTP7l2mh2Kl0aNGyNYtW2RS3DQ5cOCA9O3dU0qWKCl3NWpsemjWYA7MYw7MYw7ssnr1aqlVq5Z069ZNqlatmrG/Xr16UqFChXN+/tixYxd93xTbht143ZUydWjbc9qLShUvLHEffS/vzPxa3357xnLp2aGR1KhcmmLbRXt3x+tCO13STQ/FSsnJybJg/lwZO2GSVKhYSW/xu3bK7Fkz+QfOI8yBecyBecyByxzHk0+o1ZZZWFiY3s7n8ccfP+/+q666Sm8+hw8flkWLFkmXLl1yVhvJkSNH5NChQ/Lnn3+KberFXC///vFnub3NG1n2f7t2p3QfNV9/HRoaIm2a1dEJ+I9bfjE0UjtsWPejRFevKePjZpoeipV+3rFdTp06JVWrRmfsi64WI5s3bZQzZ84YHZstmAPzmAPzmIOcb+LEiRITE5NlU/sux4kTJ3SRrdpKHnvsscBPthcvXiwzZsyQTZs26Y/tfcLDw6Vy5crSpk0badiwoQS7SXO/+9vvq3aSjR/1ldDQXNJnzMek2i5r9khz00OwWmJCghQqVFhyZ0oeihaN0r8jkpKSpEiRIkbHZwPmwDzmwDzmIOevs92pUydp165dln0XSrUvxvHjx+XZZ5+VvXv3ygcffCARERGBXWy/9957EhsbKx06dJDOnTtL0aJF9Qug4v7ExERZs2aNvPLKK/L8889Lq1atxGaJR45J3ZYjpdZN18rwlx6S+P2J8vGyDaaHBbgi5UTKOb8MfbdPnvVxINzBHJjHHJjHHOR8YX/TMpJdqj9b1azq5Mlp06bpEyWzw0ixHRcXJ8OHDz9vcl22bFndoF6+fHm9tIrtxfafx07Ixh2/6q3CdVfKM83rU2wjaOXJk+ecHjvfbfWpF9zHHJjHHJjHHOT8nm1/UW1DKhj+9ddf5f3339d1anYZ6dlWPS+Zm83P54orrpC//vpLbKUK61ujs07ott0HpWihfMbGBLitePErJCnpiO6V9ElMTND/uBWIjDQ6NlswB+YxB+YxB/CZN2+evsDN4MGDJTIyUq+7rTbVThTQxfZdd92l20RUu0jm/5F97yDWrVsnvXv31lfpsdV99avI2L4tsuyLrni17Nhz0NiYALeVv7GChIaGyqaN//v0Zv26tVKpchUJCQmI87mDHnNgHnNgHnNg3zrbF/LVV1/p2lT1gNetWzdjy85qJEbaSAYMGKDbSNq3by+nT5+WQoUKZfRsq3cK6n/wpk2bSq9evcRWsxb9KC+3u1sGd20q7338H2lYu4K0uLfGOauWAMFEnXByf9NmMnjgABk4eKj8/vvvMn1qnLw2eJjpoVmDOTCPOTCPObDbjh07Mr6eMmXKZd+fk56ebmxB4ZSUFNm+fbuO49XXqkdKtY+oxcMvpycqIrqz5EQp62Pl7g5j9LJ/Ss0qZWTkyw9L5RtKyS+/HZa+b38qi1Zslpxg74o3Jae7rUZlGTMhTqJjakpOVDBvbsmJ1O+CIQMHyNIliyV/gfzStl17adm6relhWYU5MI85MC+Y5iA8wK6qEnGP+zVCyhfdJFAYLbbdklOL7WASDMV2TpdTi20AgH9RbJsVYC8/AAAAgppjV9+7Xc8WAAAA8BDJNgAAALzj5Jx1tv2BZBsAAABwCck2AAAAvOPYlfXa9WwBAAAAD5FsAwAAwDuOXVmvXc8WAAAA8BDJNgAAALzjsBoJAAAAAD8g2QYAAIB3HLuyXrueLQAAAOAhkm0AAAB4x6FnGwAAAIAfkGwDAADAO45dWa9dzxYAAADwEMk2AAAAvOPQsw0AAADAD0i2AQAA4BmHZBsAAACAP5BsAwAAwDMOyTYAAAAAfyDZBgAAgHccsQrJNgAAAOASkm0AAAB4xqFnGwAAAIA/kGwDAADAMw7JNgAAAAB/INkGAACAZxzLkm2KbQAAAHjGsazYpo0EAAAAcAnJNgAAALzjiFVItgEAAACXkGwDAADAMw492wAAAAD8gWQbAAAAnnFItgEAAAD4Q1Am2/+eP8T0EKxXrtNs00Ow3qH3W5keAmDc0eSTpodgvYJ5c5seAgKMQ7INAAAAwB+CMtkGAABAYHJItgEAAAD4A8k2AAAAvOOIVUi2AQAAAJeQbAMAAMAzDj3bAAAAAPyBZBsAAACecUi2AQAAAPgDyTYAAAA845BsAwAAAPAHkm0AAAB4xxGrkGwDAAAALiHZBgAAgGccerYBAAAA+APJNgAAADzjkGwDAAAA8AeSbQAAAHjGIdkGAAAA4A8k2wAAAPCMQ7INAAAAwB9ItgEAAOAdR6xCsg0AAAC4hGQbAAAAnnHo2QYAAADgDyTbAAAA8IxDsg0AAADYJy0tTZo0aSKrVq3K2Ld//35p27atVK1aVe6991757rvvsnWfFNsAAADwNNl2XN4uRWpqqrz44ouyc+fOjH3p6eny3HPPSVRUlMyfP1+aNm0qnTt3lgMHDlz0/dJGAgAAAKvt2rVLXnrpJV1cZ/bDDz/oZHv27NmSN29eKVu2rKxcuVIX3l26dLmo+ybZBgAAgHccD7ZsWr16tdSqVUvmzJmTZf/GjRulYsWKutD2iYmJkQ0bNlz0fZNsAwAAIOh6r9PS0rLsCwsL09v5PP744+fdn5CQIMWLF8+yr2jRonLw4MGLHgvFNgAAAIJqNZKJEydKbGxsln2q1/piWz98UlJSzinQ1e2zC/m/Q7ENAACAoNKpUydp165dln0XSrX/Tp48eSQpKSnLPlVoh4eHX/R9UGwDAAAgqJLtsL9pGcmOK664Qp88mVliYuI5rSV/hxMkA8jBA/tl+KtdpP2D9eX51vfLZ/PeNz0kq4SFhsjKEfdL3QpXZNl/3RUF5OC0FsbGZRu19FL/vr2lbu3qcmf9ujJtapzpIVmHOQgcKkFr81gzWb92temhWIfjAMrNN98sP/30k5w4cUJ81q5dq/dfLJLtAHHmzBkZ1a+bXFeuogyJfV8O/ne/jB3eR4oULSa33NHY9PCCXp7cITKlcz2peHWhLPtLFckrc7rfIRFhHCpeGT1qhGzdskUmxU3T65j27d1TSpYoKXc14jjwCnMQOMXewD49ZM/urKkavMFx4B4nB11BsmbNmlKiRAnp1auXPPvss/L111/Lpk2bZNiwYRd9H1QQAeJo0h9Sumw5ade5p0TkzSdXlrpGKlWtITt+2kix7bLypQrK5M515exj/77qV8uYDrXlYFKyqaFZJzk5WRbMnytjJ0ySChUr6S1+106ZPWsm/8B5hDkIDHt3x+tCO12yrvkLb3AcwCdXrlwybtw4efXVV+Whhx6S0qVLy9ixY6VkyZJysWgjCRCFi0RJl15DdaGtFlT/+aeNsn3LeqlwUzXTQwt6qm3k262H5K5+X2bZ3yi6lAyZu0FembbG2Nhs8/OO7XLq1CmpWjU6Y190tRjZvGmj/vQH7mMOAsOGdT9KdPWaMj5upumhWInjwM4rSPrs2LFDr7ntowrsGTNmyObNm+Wzzz6TW265RbKDZDsAvdC2qRz+/aBE16wrNW9tYHo4QW/K0p/Pu7/rpB/0n2f3cMM9iQkJUqhQYcmd6aSWokWj9Mfp6mzwIkWKGB2fDZiDwNDskeamh2A1jgP4E8l2AHr+1dflpQFvyC+7f5YZ775pejiAZ1JOnH89U+VkNtY0xaVjDgCOAxuvIOkmku0ApE6S9B3Q40b0k8c7PC+huXObHhbgOrWe6dkXCvDdzs6aprh0zAHAcYAgKbZ//PHHi/7ZGjVqSLA7euSw7Ny2WarfcnvGvlLXXCunTp2UlOTjUqBg1lUygGBUvPgVkpR0RPdKhob+/6+nxMQE/Y9bgchI08OzAnMAcBy4zclBq5Hk6GJ74MCBGYuEqxMC/25Ctm3bJsEu4eABGTO4p4yZvlCKRP3/Qul7dm2XyIKFKbRhjfI3VtD/sG3auEGqxVTX+9avWyuVKleRkBC63rzAHAAcB/AvY//HzJ8/X+68804pX768bNy4UbZv337ezYZC29c6Uub6G2XSm4Pkv7/slg2rv5dZU96WB5pnvdQoEMwiIiLk/qbNZPDAAbJl8yZZvmypTJ8aJ4+3bG16aNZgDgCOA9tXIwmaYludaDB69Gj99VtvvSW2C8mVS17sP0ryhEfIgBfby+QxQ+TuBx6TRk0fMz00wFMv9+glFStWkg7t2sjQwa/JM891kYZ33W16WFZhDgCOA/iPk/53PRweiI+Pl9WrV0uLFv67HPaPu4/67b5waRq++qnpIVjv0PutTA8BMO5o8knTQ7Bewbyc4G9aeIAth3H9y1+4/hi7Rt0jgcL4y1+2bFm9AQAAAMHGeLENAAAAezgB1lPtNk6pBQAAAFxCsg0AAADPOHYF2yTbAAAAgFtItgEAAOAZx7Jom2QbAAAAcAnJNgAAADzj2BVsk2wDAAAAbiHZBgAAgGdCQuyKtkm2AQAAAJeQbAMAAMAzjl3BNsk2AAAA4BaSbQAAAHjGsSzaJtkGAAAAXEKyDQAAAM84dgXbJNsAAACAW0i2AQAA4BnHsmibZBsAAABwCck2AAAAPOOQbAMAAADwB5JtAAAAeMaxK9gm2QYAAADcQrINAAAAzziWRdsk2wAAAIBLSLYBAADgGceuYJtkGwAAAHALyTYAAAA841gWbZNsAwAAAC4h2QYAAIBnHLuCbZJtAAAAwC0k2wAAAPCMY1m0TbINAAAAuIRkGwAAAJ5x7Aq2KbYBAADgHceyaps2EgAAAMAlJNsAAADwjGNXsB2cxfY1UXlND8F6h95vZXoI1tuXmGx6CNbjd5F5BfPmNj0EAJYLymIbAAAAgcmxLNqmZxsAAABwCck2AAAAPOPYFWyTbAMAAABuIdkGAACAZxzLom2SbQAAAMAlJNsAAADwjGNXsE2yDQAAALiFZBsAAACecSyLtkm2AQAAAJeQbAMAAMAzDsk2AAAAAH8g2QYAAIBnHLuCbZJtAAAAwC0k2wAAAPCMY1m0TbINAAAAuIRkGwAAAJ5x7Aq2SbYBAAAAt5BsAwAAwDOOZdE2yTYAAADgEoptAAAAeMZx3N+y67fffpNOnTpJtWrVpEGDBjJ16lS/PV/aSAAAAGC1F154QUqWLCkfffSR7Nq1S15++WUpVaqU3HXXXZd93yTbAAAA8EyI47i+ZcfRo0dlw4YN8swzz0iZMmWkYcOGUq9ePVm5cqV/nq9f7gUAAADIgcLDwyUiIkKn2idPnpTdu3fLunXrpEKFCn65f9pIAAAA4BnHg8VI0tLS9JZZWFiY3s6WJ08e6devnwwaNEimT58up0+floceekgeffRRv4yFZBsAAABBZeLEiRITE5NlU/suJD4+Xu644w6ZM2eODBs2TL788kv59NNP/TIWkm0AAAAE1TrbnTp1knbt2mXZd75UW1G92fPmzZMVK1bolpIqVarIoUOHZPz48fLAAw9c9lhItgEAABBUwsLCJH/+/Fm2CxXbW7ZskdKlS+tC26dixYpy4MABv4yFZBsAAACeCQmwC0gWL15cfvnlF93j7SvI1UmSV111lV/un2QbAAAA1mrQoIHkzp1b+vTpI3v27JHly5fLhAkTpFWrVn65f5JtAAAABFXPdnYUKFBAXzFyyJAh8sgjj0iRIkX0mtuPPfaY+APFNgAAAKx2/fXXy3vvvefKfVNsAwAAwDNOYAXbrqNnGwAAAHAJxXYAUmfDtnmsmaxfu9r0UKyTmpoq/fv2lrq1q8ud9evKtKlxpodkncMJv8uwfi9Liyb1pc3Dd8vk2FGSlppqelhW4Tgwjzkwjzlwj+PBf4GENpIAPLgH9ukhe3bvMj0UK40eNUK2btkik+Km6fU1+/buKSVLlJS7GjU2PTQrpKen60I7f4FIef2dODn251EZM3yAhOTKJU8+08308KzBcWAec2AecwB/odgOIHt3x+tCO13STQ/FSsnJybJg/lwZO2GSVKhYSW/xu3bK7Fkz+eXqkV/37ZUdWzfL9AVLpXCRonrfE08+I3Hj36TY9gjHgXnMgXnMgV3rbLuNNpIAsmHdjxJdvaaMj5tpeihW+nnHdjl16pRUrRqdsS+6Woxs3rRRzpw5Y3RstihcJEpeGzk2o9D2ST5+zNiYbMNxYB5zYB5zAH8i2Q4gzR5pbnoIVktMSJBChQpL7kyXcy1aNEq39iQlJel1N+Gu/AUKSLWat2TcVv+oLVowR26uVtPouGzCcWAec2Aec2DXOttBmWyrEwBHjhwp9evXl2rVqknnzp0lPj4+y88kJiZKhQoVTAwPlko5kZJxmVYf3+2TaWmGRmW39ya8JfE/b5dWHTqbHoo1OA7MYw7MYw6Q44vt0aNHy9KlS6VHjx4ycOBAXVg//PDDet/ZJ0sBXsmTJ49+I5iZ73Z4eLihUdlr6oQx8um8D+TFPoOl9HXXmx6ONTgOzGMOzGMO3OU47m9ie7H9xRdfyNChQ+W+++6TJk2ayKxZs6RFixbywgsv6O/Z+jEDzCpe/ApJSjqi+/R8EhMT9C/WApGRRsdmm4lvvS4LPnxfXnp1sNxav6Hp4ViF48A85sA85gA5vtg+ceKEFCpUKEtR3bNnT2nTpo10795dlixZYmJYsFz5GytIaGiobNq4IWPf+nVrpVLlKhISwrnEXpk1daJ88el86dFvmNx2J2f9e43jwDzmwDzmwF0hjuP6FkiM/B9Tq1YtGTFihPzxxx9Z9qtC+7HHHpNu3brJBx98YGJosFhERITc37SZDB44QLZs3iTLly2V6VPj5PGWrU0PzRr79+6W2dMnySNPtJWKVaLlyOHEjA3e4DgwjzkwjzmAPznpBhqjDx06JF27dpVNmzbJ5MmT5dZbb83y/djYWBk/frxeiWDbtm3Zv/8/T0pOd1uNyjJmQpxEx+TMVRgK5s0tOVFKSooMGThAli5ZLPkL5Je27dpLy9ZtJSfal5gsOc3cmXEy/d13zvu9hSvWS05zTVReyYmC6TjIqZgD84JpDsIDbO25h+PWuv4Y85+MEauLbZ/du3dLsWLFpECBAud8T61OsmzZMunYsaOVxXZOl1OL7WCSE4vtYJNTi20AwYVi2yyjL/911113we+VLVtWbwAAAAgeToD1VLuNLn8AAADAJQH2wQIAAACCmWNXsE2yDQAAALiFZBsAAACeCbEs2ibZBgAAAFxCsg0AAADPOGIXkm0AAADAJSTbAAAA8IxDzzYAAAAAfyDZBgAAgGdC7Aq2SbYBAAAAt5BsAwAAwDMOPdsAAAAA/IFkGwAAAJ5x7Aq2SbYBAAAAt5BsAwAAwDOOZdE2yTYAAADgEpJtAAAAeCbErmCbZBsAAAAwmmz36tXrou9w2LBhlzMeAAAABDGHnm0AAAAAniXbpNUAAADwB0fsku0TJNPT02XZsmWyc+dOOX36dMb+tLQ02bp1q0yePNnfYwQAAADsKLYHDRok8+bNk4oVK8qmTZskOjpa9u3bJ4mJidKiRQt3RgkAAICgEELP9t/7/PPPZdSoUTJ79my55pprZMCAAfL111/LfffdJydPnnRnlAAAAIANxfaxY8ekcuXK+uty5crpdDs0NFQ6deokK1ascGOMAAAACBKO4/6Wo4vtq6++WvdmKzfccIMutn293H/99Zf/RwgAAADY0rP95JNPSvfu3WXIkCFy7733ykMPPaST7fXr10tMTIw7owQAAEBQcAIteg60YvvRRx+VMmXKSN68eaVs2bISGxsrc+fO1a0lXbp0cWeUAAAAgA3FtlKjRo2Mr+vVq6c3AAAA4J84dgXb2S+2W7Vq9bfx//Tp0y93TAAAAICdxXatWrWy3D516pTs379fr0TyzDPP+HNsAAAACDIhlkXb2S62O3fufN79H330kSxevFjat2/vj3EBAAAAOV62l/77uz7ulStX+uvuAAAAEIQcy9bZznayfeDAgXP2HT9+XKZMmSKlSpXy17gAAACAHC/bxXaDBg3OOUFSXdCmRIkSeu1tAAAA4EKcQIueA63YXrZs2TkvWO7cuSUqKsq6Fw8AAADwa7Hdq1cvfSGbyMjILPv/+OMP6dChgz5R0rSCeXObHoL1jiafND0E610Tldf0EKy3LzHZ9BCsx3EABPEJg8FUbP/73/+WTZs26a9//PFHmTBhgr6CZGa//PKL/Pe//3VnlAAAAECwFtvXXnutTJ48Wfdmq23dunW6dcRHtY+o4puebQAAAPwdx7K244sqtq+++uqMK0OqNpJXX31V8ufP7/bYAAAAEGRC7Kq1s98289prr8m4ceNk5syZGfseeughGTVqlJw8SZ8uAAAAcMnF9uDBg/Wl2W+88caMfc8++6x88803Mnz48OzeHQAAACxLtkNc3nJ0sa0uya5S7JiYmIx9DRs2lGHDhsnnn3/u7/EBAAAA9iz9p06QTE1NPe9+2kgAAADwdxzLTpDMdrLdqFEj6du3r6xZs0aSk5P1plYnGTBggE64AQAAAFzGRW3UaiRt2rSRM2fO6EQ7NDRUmjVrJs8991x27w4AAAAWCbEr2M5+sR0RESGjR4+WP//8U1/I5vTp07J3715ZuHChTrZ/+uknd0YKAAAABHux7bNz5075+OOP5csvv5Rjx45J2bJlpXfv3v4dHQAAAIKKQ7J9Yepy7KrA/uSTT2T//v0SGRmpC+033nhD7r33XvdGCQAAAARrsT1//nxdZKuTIosXLy4NGjSQu+++W2rUqCE333yzlCtXzv2RAgAAIMcLsSzavqhiW50QWbp0aX3RmgceeMD9UQEAAAAeSUtL09eM+eyzzyR37tzyyCOPSLdu3fyyTOFFLf03dOhQueqqq/RKJHXq1NF/Llu27LzrbQMAAAB/V3yGuLxdyhXS//Of/8iUKVN0e/SHH34oc+bM8S7Zfuihh/T2xx9/yBdffKGvFNm5c2cJDw/Xy/+tWrVKJ9/qnQAAAACQUyQlJemW6ffee09uuukmve/JJ5+UjRs3SvPmzS/7/p10tVD2JTh48KCO2lXhvXXrVilUqJA0bdpUp96mnThlegQ4mszVRE0rmJc3v6btS0w2PQTrXROV1/QQAOPCL3ntOXe8+sXPrj/GkHsu/nxC1a2hVtRT4bEbLiVp16688krp0KGDfPTRR3r5v5YtW8q3337r39EBAAAAl9CDrVbMy7ypfeejVtgrVaqUXgykcePGcuedd8rYsWN194Y/+OW9TpkyZXRbidoAAAAAk6uRTJw4UWJjY7PsU3Vqly5dzvnZ5ORkfaHG2bNn65MkExISpF+/fvpCjqqd5HIF2AcLAAAAwOXp1KmTtGvXLsu+sLCw8/5saGhoxnVjVMKtHDhwQGbNmkWxDQAAgJzF8WCZbVVYX6i4PluxYsUkT548GYW2cu2118pvv/1mtmcbAAAAyOluvvlmvZz1nj17Mvbt3r07S/F9OSi2AQAA4JkQx/0tO6677jq5/fbb9Yp627dv1wt+vPvuu9KiRQu/PF/aSAAAAGC1UaNGyaBBg3SBrU6MfOKJJ6RVq1Z+uW+KbQAAAATVaiTZVaBAARkxYoS4gTYSAAAAwCUk2wAAAPCME3jBtqtItgEAAACXkGwDAADAMyEk2wAAAAD8gWQbAAAAnnHErmibZBsAAABwCck2AAAAPBNiV7BNsg0AAAC4hWI7gKSmpkr/vr2lbu3qcmf9ujJtapzpIVkrLS1N2jzWTNavXW16KNbhODDvcMLvMqzfy9KiSX1p8/DdMjl2lKSlppoellU4DsxjDtxNtkNc3gIJbSQBZPSoEbJ1yxaZFDdNDhw4IH1795SSJUrKXY0amx6adb9gB/bpIXt27zI9FCtxHJiVnp6uC+38BSLl9Xfi5NifR2XM8AESkiuXPPlMN9PDswbHgXnMAfyFYjtAJCcny4L5c2XshElSoWIlvcXv2imzZ83kwPbQ3t3xutBOl3TTQ7ESx4F5v+7bKzu2bpbpC5ZK4SJF9b4nnnxG4sa/SbHtEY4D85gDdzmWXUKSNpIA8fOO7XLq1CmpWjU6Y190tRjZvGmjnDlzxujYbLJh3Y8SXb2mjI+baXooVuI4MK9wkSh5beTYjELbJ/n4MWNjsg3HgXnMAYI22Vb/Yx87dkwKFSoktklMSJBChQpL7rCwjH1Fi0bploakpCQpUqSI0fHZotkjzU0PwWocB+blL1BAqtW8JeO2KiwWLZgjN1eraXRcNuE4MI85cFeIXcG2uWR70aJFMnDgQPnqq690j+DgwYOlWrVqUqdOHbn11ltlxowZYpOUEykSlumgVny3T6alGRoV4C2Og8Dz3oS3JP7n7dKqQ2fTQ7EGx4F5zAFyfLI9ZcoUGT9+vC6s+/fvLx9//LFs27ZNRo4cKddff71s3rxZRo0apXumOnbsKDbIkyePXgEjM9/t8PBwQ6MCvMVxEFimThgjn877QHr0f11KX3e96eFYg+PAPObAXY5lybaRYnvmzJkyevRoue2222Tt2rXSsmVLmTBhgtSvX19/v2zZslK4cGHp27evNcV28eJXSFLSEd1KExr6/9OSmJigD+oCkZGmhwd4guMgcEx863X5/NN58tKrg+XW+g1ND8cqHAfmMQfI8W0kR44ckTJlyuivY2JipESJEhIVFZXlZ6666ipJSUkRW5S/sYI+oDdt3JCxb/26tVKpchUJCeE8VtiB4yAwzJo6Ub74dL706DdMbruTlRe8xnFgHnPgrhDHcX0LJEb+j1G92WPHjtVtIsry5culUqVKGd///fffZdiwYbrNxBYRERFyf9NmMnjgANmyeZMsX7ZUpk+Nk8dbtjY9NMAzHAfm7d+7W2ZPnySPPNFWKlaJliOHEzM2eIPjwDzmAP7kpKuzEz22b98+3R5SsWJF3U6S2dKlS6VLly5SuXJlGTdunBQrVizb93/ilORIKskfMnCALF2yWPIXyC9t27WXlq3bSk50NPmk5HS31agsYybESXRMzlyFoWDe3JITBdNxsC/x/wOFnGTuzDiZ/u475/3ewhXrJae5Jiqv5ETBdBzkVME0B+EBtfacyNvf7XH9MbrWvVasLrYV9bCJiYnnFNOHDx+WX3/9VapUufSPanJqsR1MgqHYzulyarEdTHJisR1scmqxDfgTxbZZoSavHnS+1Lpo0aJ6AwAAQPBxAqul2nV0+QMAAAAuCbAPFgAAABDMQsSuaJtkGwAAAHAJyTYAAAA849gVbJNsAwAAAG4h2QYAAIBnQki2AQAAAPgDyTYAAAA8E2JZ0zbJNgAAAOASkm0AAAB4xrEr2CbZBgAAANxCsg0AAADPhFgWbZNsAwAAAC4h2QYAAIBnHLuCbZJtAAAAwC0k2wAAAPBMiNjFtucLAAAAeIZkGwAAAJ5xLGvaJtkGAAAAXEKyDQAAAM84YheSbQAAAMAlJNsAAADwTAg92wAAAAD8gWQbAAAAnnHELiTbAAAAgEtItgEAAOAZx7Jom2QbAAAAcAnJNgAAADzjWBZtk2wDAAAALiHZBgAAgGdCxC62PV8AAADAMyTbAAAA8IxDzzYAAAAAfyDZBgAAgGccsQvJNgAAAOASkm0AAAB4xrGsZ5tiG64omDe36SEAxl0Tldf0EKy3LzHZ9BCsx3EA21FsAwAAwDMhYhfbni8AAADgGZJtAAAAeMaxrGebZBsAAABwCck2AAAAPOOIXUi2AQAAAJdQbAMAAMAzjuP+dqk6duwor7zyij+fLsU2AAAAvBMijuvbpVi0aJGsWLHChecLAAAAWCwpKUlGjBghVapU8ft9c4IkAAAAPOME4BmSw4cPl6ZNm8rvv//u9/sm2QYAAIC1Vq5cKWvWrJFnn33Wlfsn2QYAAIBnHA8W/0tLS9NbZmFhYXrLLDU1Vfr37y/9+vWT8PBwV8ZCsg0AAICgMnHiRImJicmyqX1ni42NlcqVK0u9evVcG4uTnp6eLkHmxCnTIwAABIJ9icmmh2C9a6Lymh6C9cIDrI/h85/83xd9toY3FLqoZLtBgwaSmJgouXLl0rd9f0f93Pr16/0ylgB7+QEAAIDLc77C+nzef/99OXXqfyntqFGj9J8vv/yy+AvFNgAAADwTEkAXbC9VqlSW2/ny5dN/li5d2m+PQc82AAAA4BKSbQAAAFi9zrbP66+/Lv5Gsg0AAAC4hGQbAAAAnnECONl2A8k2AAAA4BKSbQAAAATVFSQDCck2AAAA4BKSbQAAAHgmxK5gm2QbAAAAcAvJNgAAADzj0LMNAAAAwB9ItgEAAOAZx65gm2QbAAAAcAvJNgAAADzj0LMNAAAAwB9ItgEAAOCZELuCbZJtAAAAwC0k2wAAAPCMQ882TElNTZX+fXtL3drV5c76dWXa1DjTQ7IOc2Aec2Aec2De4YTfZVi/l6VFk/rS5uG7ZXLsKElLTTU9LKtwHMBfSLYDyOhRI2Trli0yKW6aHDhwQPr27iklS5SUuxo1Nj00azAH5jEH5jEHZqWnp+tCO3+BSHn9nTg59udRGTN8gITkyiVPPtPN9PCswXHgHseuYJtiO1AkJyfLgvlzZeyESVKhYiW9xe/aKbNnzeTA9ghzYB5zYB5zYN6v+/bKjq2bZfqCpVK4SFG974knn5G48W9SbHuE4wD+RBtJgPh5x3Y5deqUVK0anbEvulqMbN60Uc6cOWN0bLZgDsxjDsxjDswrXCRKXhs5NqPQ9kk+fszYmGzDceAux4MtkFBsB4jEhAQpVKiw5A4Ly9hXtGiU7hlLSkoyOjZbMAfmMQfmMQfm5S9QQKrVvCXjtiruFi2YIzdXq2l0XDbhOEBQF9vVqlWT/fv3i21STqRIWKaDWvHdPpmWZmhUdmEOzGMOzGMOAs97E96S+J+3S6sOnU0PxRocB+4KcRzXN7G9Z7tXr14X/F5aWpqMHDlS8uXLp28PGzZMbJAnTx793DPz3Q4PDzc0KrswB+YxB+YxB4Fl6oQx8um8D6RH/9el9HXXmx6ONTgOkOOT7cOHD8uCBQskPj7exMMHpOLFr5CkpCO6R8wnMTFBH9QFIiONjs0WzIF5zIF5zEHgmPjW67Lgw/flpVcHy631G5oejlU4DtzlWNazbSTZfvfdd2XRokU6wa5Tp44899xzGR/PfPnll9K9e3e5+uqrxSblb6wgoaGhsmnjBqkWU13vW79urVSqXEVCQgKu2ycoMQfmMQfmMQeBYdbUifLFp/OlR79hcuvtd5kejnU4DuBPxv6Pue++++STTz6RhIQEuf/+++U///mP2CwiIkLub9pMBg8cIFs2b5Lly5bK9Klx8njL1qaHZg3mwDzmwDzmwLz9e3fL7OmT5JEn2krFKtFy5HBixgZvcBy4zLEr2nbS1er5hq1cuVIGDBgglStXlmXLlsnChQsvK9k+8b9PfXKUlJQUGTJwgCxdsljyF8gvbdu1l5at25oellWYA/OYA/OCaQ72JSZLTjN3ZpxMf/ed835v4Yr1ktNcE5VXcqJgOg7CA+yqKj/Eu7+iS+2yhSRQBESx7Tvx4J133pHPP/9cZsyYISVKlLCu2AYA+FdOLLaDTU4ttoNJoBXbq+KPuv4YtcoWlEARMMW2P1FsAwAUim3zKLbNo9g2K8BefgAAAAQzJ8B6qt3GKbUAAACAS0i2AQAA4BlH7EKyDQAAALiEZBsAAADeccQqJNsAAACAS0i2AQAA4BnHsmibZBsAAABwCck2AAAAPOPYFWyTbAMAAABuIdkGAACAZxyxC8k2AAAA4BKSbQAAAHjHEauQbAMAAAAuIdkGAACAZxzLom2SbQAAAMAlJNsAAADwjGNXsE2yDQAAALiFZBsAAACeccQuJNsAAACAS0i2AQAA4B1HrEKyDQAAALiEZBsAAACecSyLtkm2AQAAAJeQbAMAAMAzjl3BNsk2AAAA4BaSbQAAAHjGEbuQbAMAAAAuIdkGAACAdxyxCsk2AAAA4BKSbQAAAHjGsSzaJtkGAAAAXEKyDQAAAM84dgXbJNsAAACAW0i2AQAA4BlH7EKyDQAAALiEZBsAELSuicpregjWG7TkZ9NDsN6Qe8pJQHHEKiTbAAAAsNahQ4eka9euUrNmTalXr54MGzZMUlNT/Xb/JNsAAACwcp3t9PR0XWhHRkbKzJkz5ejRo9K7d28JCQmRnj17+uUxSLYBAABgpd27d8uGDRt0mn3DDTdI9erVdfH92Wef+e0xSLYBAABg5TrbxYoVk8mTJ0tUVFSW/ceOHfPbY5BsAwAAwEqRkZG6T9vnzJkzMmPGDKldu7bfHoNkGwAAAJ5xPHiMtLQ0vWUWFhamt78zcuRI2bp1q8ybN89vYyHZBgAAQFCZOHGixMTEZNnUvn8qtKdNm6b/LFfOf8slkmwDAAAgqKLtTp06Sbt27bLs+7tUe9CgQTJr1ixdaDdq1MivY6HYBgAAQFAJu4iWEZ/Y2FiZPXu2jB49Who3buz3sVBsAwAAwMp1tuPj42XcuHHSsWNH3WqSkJCQZaUSf6DYBgAAgJWWLVsmp0+flvHjx+stsx07dvjlMSi2AQAAYOU62x07dtSbm1iNBAAAAHAJyTYAAAA844hdKLYBAADgHUesQhsJAAAA4BKSbQAAAFi59J8XSLYBAAAAl5BsAwAAwMql/7xAsg0AAAC4hGQbAAAAnnHELiTbAAAAgEtItgEAAOAdR6xCsg0AAAC4hGQbAAAAnnEsi7ZJtgEAAACXkGwDAADAM45dwTbJNgAAAOAWkm0AAAB4xhG7kGwDAAAALiHZBgAAgGccy6Jtkm0AAADAJSTbAAAA8JAjNiHZBgAAAFxCsg0AAADPOHYF2yTbgSQ1NVX69+0tdWtXlzvr15VpU+NMD8k6zIF5zIF5zIF5zIF5p0+dlPXzxssnvZrLwj6tZPNn0yU9Pd30sJADkWwHkNGjRsjWLVtkUtw0OXDggPTt3VNKligpdzVqbHpo1mAOzGMOzGMOzGMOzNv40bvy+85NUu/pgXIyNUVWTRsh+QoXk+tuvcf00HI8R+xCsR0gkpOTZcH8uTJ2wiSpULGS3uJ37ZTZs2byy9UjzIF5zIF5zIF5zIF5acf/kj0/LJHbnh0kRUqX0/vK3dFM/vjlZ4pt5Ow2EvXxzJEjR8RGP+/YLqdOnZKqVaMz9kVXi5HNmzbKmTNnjI7NFsyBecyBecyBecyBeYl7tkruiLxS7PoqGftubPioVH/8eaPjCqaebcflTWwvtp9//nk5duxYxu2TJ0/K0KFDJTo6Wm655RapU6eOxMXZ1Z+WmJAghQoVltxhYRn7ihaN0n17SUlJRsdmC+bAPObAPObAPObAvOOJByVfkSvkl9XL5auhT8sXgzrI1q9mSzpvdpBT2kgWL14s/fr1k/z58+vbb7/9tt43YsQIKVu2rGzdulVGjhwpJ06ckGeffVZskHIiRcIy/WJVfLdPpqUZGpVdmAPzmAPzmAPzmAPzTqWdkL8SDsjulV9K9RYvyIk//5C1H46V0LA8Uu6OB00PL8dzLOvaNlJsn30275dffil9+vSRhg0b6tuq4I6MjJS+fftaU2znyZNH0s76Jeq7HR4ebmhUdmEOzGMOzGMOzGMOzHNCQuTUiWSp2eplyVekuN6XfCRB4r//nGIbOaONxHEcvWUMIiRErrrqqiw/c80118jx48fFFsWLXyFJSUd0n55PYmKC/sVaIDLS6NhswRyYxxyYxxyYxxyYFx5ZREJyh2UU2kr+4qUkOSnR6LiChuPBZnuxrZJtlWS/+eab8vHHH0vlypVl+vTpGd9XfWljx46VqlWrii3K31hBQkNDZdPGDRn71q9bK5UqV9FvRuA+5sA85sA85sA85sC8oqXLy5mTafLX7//N2PfXoV8lX+H/Fd/AxTJy1MbGxspNN92k1w5VRfby5ctlwYIF8ueff+rv33bbbbJmzRrp3bu32CIiIkLub9pMBg8cIFs2b5Lly5bK9Klx8njL1qaHZg3mwDzmwDzmwDzmwLwCV1wlV1asLj9+8JYk/XePHNy2TnYsm8eyf37i2BVsi5MeIJdDUoV3yZIl9dffffedXpkkX758l3RfJ/73yVuOkpKSIkMGDpClSxZL/gL5pW279tKydVvTw7IKc2Aec2Aec2BeMM3BoCU/S050MuW4rJ8/UQ5s/kFy5c4jZeveKxUaNc/SBptTDLnn/9cKDxSH/jzp+mNcEZlbAkXAFNv+lFOLbQAAgk1OLbaDSaAV27//5X6xXbxA4BTbNH8BAAAALuFy7QAAAPCME3Bd1e4i2QYAAABcQrINAAAA7zhiFZJtAAAAwCUk2wAAAPCMI3Yh2QYAAABcQrINAAAAzziWRdsk2wAAAIBLSLYBAADgGceyrm2SbQAAAMAlJNsAAADwjGNXsE2yDQAAALiFYhsAAABwCcU2AAAA4BJ6tgEAAOAZh55tAAAAAP5Asg0AAADPOKyzDQAAAMAfSLYBAADgGceuYJtkGwAAAHALyTYAAAA844hdSLYBAAAAl5BsAwAAwDuOWIVkGwAAAHAJyTYAAAA841gWbZNsAwAAAC4h2QYAAIBnHLuCbZJtAAAAwC0k2wAAAPCMI3Yh2QYAAABcQrENAAAAb6Ntx+Utm1JTU6V3795SvXp1qVu3rsTFxfnt6dJGAgAAAKuNGDFCtmzZItOmTZMDBw5Iz549pWTJktK4cePLvm+KbQAAAFi7znZycrLMnTtXJk2aJJUqVdLbzp07ZebMmX4ptmkjAQAAgLW2b98up06dkujo6Ix9MTExsnHjRjlz5sxl3z/FNgAAADxdZ9txecuOhIQEKVy4sISFhWXsi4qK0n3cSUlJl/18aSMBAABAUElLS9NbZqqYzlxQ+6SkpJyz33f77Pu4FEFZbIcH5bMCACDnGXJPOdNDgIV12jvvTJTY2Ngs+zp37ixdunQ552fz5MlzTlHtux0eHn7ZY6EsBQAAQFDp1KmTtGvXLsu+86XayhVXXCFHjhzRfduhoaEZrSWq0I6MjLzssdCzDQAAgKASFhYm+fPnz7JdqNiuUKGCLrI3bNiQsW/t2rVSpUoVCQm5/FKZYhsAAADWioiIkGbNmsmAAQNk06ZNsnTpUn1Rm9atW/vl/p309PR0v9wTAAAAkAOlpKToYnvx4sU6BW/fvr20bdvWL/dNsQ0AAAC4hDYSAAAAwCUU2wAAAIBLKLYBAAAAl1BsBxB1WdDevXtL9erVpW7duvpMWJihFrNv0qSJrFq1yvRQrHPo0CHp2rWr1KxZU+rVqyfDhg3Txwa888svv+iTg6Kjo+X222+XyZMnmx6S1Tp27CivvPKK6WFYZ8mSJVK+fPksm/rdBGQXF7UJICNGjJAtW7bItGnT5MCBA9KzZ08pWbKkNG7c2PTQrKIKu5deekl27txpeijWUedrq3/M1EUEZs6cKUePHtVvQNU6p+p4gPvOnDmjizu1vuyCBQt04f3iiy/qiz7cf//9podnnUWLFsmKFSvkwQcfND0U6+zatUvuuOMOGTRoUJYrDQLZRbEdIJKTk2Xu3LkyadIkqVSpkt5UsacKDoptb3+5qkKbRXrM2L17t76owPfffy9RUVF6nyq+hw8fTrHtkcTERH2BB7UEllr+qkyZMlKnTh19gQeKbW8lJSXpEEa98YH34uPjpVy5clKsWDHTQ0EORxtJgNi+fbu+TKj62NYnJiZGNm7cqJMmeGP16tVSq1YtmTNnjumhWEn9o6ZaFnyFts+xY8eMjck2xYsXl7feeksX2upNpyqyf/zxR93WA2+pN5lNmzaV66+/3vRQrC221ZtN4HKRbAeIhIQEKVy4cJZLiaqCQ7U0qHSjSJEiRsdni8cff9z0EKym2kdUn7aPeqM5Y8YMqV27ttFx2apBgwa6pU19lN6oUSPTw7HKypUrZc2aNbJw4UL9KQO8pd5o7tmzR7777juZOHGinD59Wn/KrD5pu9Alv4ELIdkOoCsXnX0A+26rk/UAG40cOVK2bt0q3bp1Mz0UK7399tsyYcIE2bZtmz5RFd5QIUv//v2lX79+Eh4ebno4VlJvMn3/LqtPelQbm3rjo9p6gOwi2Q4Q6qSLs4tq321+2cLWQludLPzmm2/qvkl4z9crrIq/l19+WXr06EGq54HY2FipXLlylk954K1SpUrp1agKFiwojuPo8xjUJ23du3eXXr16Sa5cuUwPETkIxXaAUGf6HzlyRPdth4aGZrSWqEJbfbQO2ESd/T9r1ixdcNO+4P0Jkuok1YYNG2bsUz3DJ0+e1L3ztLR5swKJmgffOTy+4OWrr76S9evXGx6dPQoVKpTldtmyZfUbT7VKEscBsoM2kgCh3jWrIlv9I+ejTkxSyZJa9gywKdWbPXu2jB49Wu677z7Tw7HOr7/+Kp07d9brnfuoJUlVcUGB4Y33339ftyx8/PHHelO982pTX8Mb3377rT5ZXrWS+Kh2KlWAcxwgu6jiAkRERIQ0a9ZMnwizadMmWbp0qb6oTevWrU0PDfD07P9x48bJU089pVfjUZ/u+DZ4Q73BV0uPqvXN1VKYao1n9QnD008/bXpoVrUwlC5dOmPLly+f3tTX8Ib6VEG1d/bp00cvSaqOA9Wv3aFDB9NDQw5EG0kAUX1gqthu06aNXnarS5cucvfdd5seFuCZZcuW6bP+x48fr7fMduzYYWxcNlG9qOoNj2rleeyxx3QQ0KpVK974wyrq3+ApU6bI0KFD5eGHH9Zvdpo3b06xjUvipHP1DgAAAMAVtJEAAAAALqHYBgAAAFxCsQ0AAAC4hGIbAAAAcAnFNgAAAOASim0AAADAJRTbAAAAgEsotgEAAACXUGwDsEaDBg2kfPnyGZu6LHnjxo1l6tSpfnsMdbXFd955R3/9yiuv6O2fpKWlyYcffnjJj/nRRx/p5wYACDxcrh2AVXr37i333nuv/vrUqVPyww8/yKuvviqFChWSZs2a+fWx1P1ejEWLFsmECRPkX//6l18fHwBgHsk2AKsUKFBAihUrprcSJUrIgw8+KHXq1JHFixe78lhq+yfp6el+f2wAQGCg2AZgvdDQUMmdO7duARk0aJDceeedcvvtt8uxY8fkt99+k6efflpuvvlm3aoRGxsrp0+fzvi7S5YskUaNGknVqlVl4MCBWb53dhvJJ598ottW1H01b95ctm7dKqtWrZJevXrJf//7X93a8uuvv+rie+zYsVK3bl2pXr26fvwDBw5k3M+hQ4ekQ4cO+jHVm4V9+/Z5+GoBALKDYhuAtU6ePKkT7e+//14X2L7+55EjR+qiOl++fNK5c2cpWrSoLFiwQIYNGyYLFy7ULR/Krl275IUXXpAWLVrI/PnzdVvK2rVrz/tY3377rW4radOmjXz66adSuXJl6dSpk0RHR+vWliuvvFK+++47nbbPmDFDP84bb7whc+bM0Y//5JNP6vEqzz//vJw5c0bmzp0rTz31lEybNs3DVw0AkB30bAOwSv/+/XV6rZw4cULCw8N1AfzAAw/o4lUl2tWqVdPfX7lypU6U1f6QkBC57rrrpGfPnjqJfu6553SBrZLntm3b6p/v27evfP311+d9XFU0N2nSRBfmSo8ePXSafvToUd1qkitXLt3aokyePFmPs1atWvq2SsxVyq0K9quvvlrWr1+vH6dkyZJyww03yJYtW+TLL7/05PUDAGQPxTYAq3Tt2lXuvvtu/XWePHl0gasKXZ9SpUplfB0fHy9JSUkSExOTsU8lyqpIP3LkiP5+hQoVMr6niufMtzPbs2ePbh3xCQsL04X72Y4fPy4HDx6Ubt266QLfRz3m3r17JTU1VZ/MqQptnypVqlBsA0CAotgGYBXVklG6dOkLfl8V4D6qLUSl2ePGjTvn53wnPp59cqMquC/UF34xfD3fY8aMkWuvvTbL9woWLKjT9ot9TACAefRsA8AFqGJXtZEUKVJEF+hqUycwvv322+I4jm7h2Lx5c5bUe/v27ee9L/V3M39PFdXqhEvV463uyycyMlK/IUhISMh4TNXHrfrIVTperlw53Xryyy+/ZPydbdu2ufYaAAAuD8U2AFyA6pNWbSXdu3eXHTt2yJo1a3RfdkREhG49Uetiq37p8ePHy+7du2X48OFZVg3JTK10ok6MVCdaqkJZnWypEmp1YR11f6qAVm0iKk1XPeBvvfWWLF++XO/r06ePrFu3TqfsZcuW1UsVqpMqVfG+dOlSfUIlACAwUWwDwAWogloV0iqxVoV1ly5dpH79+rr4VVTqrL6vLkqjLoij0mj1/fOpUaOGPulRLemnTsZUabRa1USdoFm7dm19X/fff7/e3759e3nkkUekX79++n5VAT9lyhTdRqK8+eabUrhwYd0DPnr0aF3IAwACk5PO1RQAAAAAV5BsAwAAAC6h2AYAAABcQrENAAAAuIRiGwAAAHAJxTYAAADgEoptAAAAwCUU2wAAAIBLKLYBAAAAl1BsAwAAAC6h2AYAAABcQrENAAAAuIRiGwAAABB3/B+0Z/SmxsCuMwAAAABJRU5ErkJggg=="
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "execution_count": 9
  },
  {
   "metadata": {
    "ExecuteTime": {
     "end_time": "2025-07-22T22:46:02.649005Z",
     "start_time": "2025-07-22T22:46:02.620715Z"
    }
   },
   "cell_type": "code",
   "source": [
    "joblib.dump(model, \"glass_model.pkl\")\n",
    "joblib.dump(scaler, \"scaler.pkl\")\n",
    "print(\"✅ Model and Scaler saved as glass_model.pkl and scaler.pkl\")"
   ],
   "id": "29a5d0c0d8909352",
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "✅ Model and Scaler saved as glass_model.pkl and scaler.pkl\n"
     ]
    }
   ],
   "execution_count": 12
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
